sudo: false

addons:
  apt:
    packages:
      - libipc-run3-perl
  coverity_scan:
    project:
      name: "maxmind/libmaxminddb"
      description: "Build submitted via Travis CI"
    notification_email: dev@maxmind.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: .*coverity.*

language: c

compiler:
  - clang
  - gcc

before_script:
  - ./bootstrap
  - CFLAGS="-std=c99 -Wall -Wextra -Werror -Wno-unused-parameter" ./configure
  - make

script:
  - export VERBOSE=1
  - make check

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   - secure: "a2pXNVW/lGrMdJTal+pzH0J5N69RdBErwe2dHU2xDnOeNcDYmiSxmU4Fw52KPYXFzdlR9GuEyZtHtesRQthSHpylcIvfJJCih7EvwbNQ5pfplpT5ri2PKPFWB11ebr6vG23Ucgc5lrqHdgIgv+QtqVmW1IDf0hq62itMpu4MwcQ="
